### ISSUE TITLE
Themosis framework is actived or not?

### ISSUE THREAD

**Issue by ghost** [themosis/todo#2]
Activating this theme I get the message: **You first need to activate the Themosis framework in order to use this theme**, but the offical documentation of themosis report 

**Note: the themosis-framework package is installed inside the mu-plugins folder. So there is no need to activate it once WordPress is installed.**

The plugin should be active or not?

**Comment by jlambe** [comment]
This project has not been updated for a long time and was a demo for the previous Themosis framework 1.1 or 1.2.

I can't tell you much more at the moment has this project has no update planned at the moment. If you're trying the framework for the first time, I suggest you to read current code the Bookstore project even if not yet completed and also install a bare project and explore the APIs.

If you have any questions regarding the framework, you can contact us at support@themosis.com and if you met any issues during development that relates to the framework, you can report issues on the `themosis/framework` repository.

Cheers,
